services:
  frontend:
    build:
      context: .
      target: ${TARGET}
    ports:
      - "5173:5173"
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}

  tests:
    build:
      context: .
      target: test
    depends_on:
      - frontend
    environment:
      - NODE_ENV=test